version: "0.2"
language: en
words:
  - androideabi
  - armv
  - autoupdate
  - binstall
  - bndy
  - capfd
  - cbindgen
  - cdylib
  - clippy
  - cooldown
  - crossrefs
  - ctest
  - Doherty
  - Doxyfile
  - dtolnay
  - eabi
  - emnapi
  - endfor
  - endforeach
  - endmacro
  - fontawesome
  - getattr
  - gnueabi
  - gnueabihf
  - Heroicons
  - hustcer
  - inlinehilite
  - isnan
  - libc
  - libnghttp
  - linenums
  - manylinux
  - maturin
  - mkdocs
  - mkdocstrings
  - mlugg
  - msvc
  - multiarch
  - musleabihf
  - mypy
  - napi
  - nextest
  - nonconstructor
  - nonoctal
  - npmjs
  - nurfile
  - nushell
  - ohos
  - openharmony
  - orhun
  - oxlint
  - patchelf
  - pipx
  - pwsh
  - pyclass
  - pyfunction
  - pymdownx
  - pymethods
  - pymodule
  - pypa
  - pypi
  - pyproject
  - pytest
  - pyyaml
  - repr
  - reshim
  - riscv
  - rustc
  - rustdoc
  - rustflags
  - rustup
  - sccache
  - scrollbars
  - sdist
  - setattr
  - staticlib
  - stdint
  - STREQUAL
  - superfences
  - taiki
  - tasklist
  - timeit
  - tlsv
  - topo
  - twemoji
  - tybys
  - venv
  - WASI
  - wasip
  - Werror
  - yarnrc
  - zigbuild
ignorePaths:
  - .env/**
  - .venv/**
  - env/**
  - venv/**
  - target/**
  - "**/.gitignore"
  - .yarn/releases/*
  - docs/docs/images/Key--Streamline-Heroicons.svg
  - bindings/cpp/Doxyfile
